/*
 * SonicOS API
 *
 * __Swagger Specification for SonicOS APIs__  ___SonicOS support two-factor and bearer token login from SWAGGER only.___  Please follow the following steps to login. > 1. POST \"tfa\" with your username, password, and two-factor code to the firewall. If you are authenticating a username for the first time, please login to GUI and scan the QR code to activate two-factor authentication. > 2. The Bearer Token is returned in response to the \"tfa\" message. Copy the Bearer Token to the \"Authorize\" button. > 3. DELETE \"auth\" to logout of the current session. 
 *
 * The version of the OpenAPI document: 7.0.1
 * Contact: sonicOsApiSupport@SonicWall.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = SonicWallGen7.Client.OpenAPIDateConverter;

namespace SonicWallGen7.Model
{
    /// <summary>
    /// Enable restricting transfer of MS-Office type files containing macros (VBA 5 and above).
    /// </summary>
    [DataContract(Name = "gateway_antivirus_gateway_antivirus_restrict_ms_office_macros")]
    public partial class GatewayAntivirusGatewayAntivirusRestrictMsOfficeMacros : IEquatable<GatewayAntivirusGatewayAntivirusRestrictMsOfficeMacros>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GatewayAntivirusGatewayAntivirusRestrictMsOfficeMacros" /> class.
        /// </summary>
        /// <param name="http">HTTP..</param>
        /// <param name="ftp">FTP..</param>
        /// <param name="imap">IMAP..</param>
        /// <param name="smtp">SMTP..</param>
        /// <param name="pop3">POP3..</param>
        /// <param name="cifsNetbios">CIFS/NetBIOS..</param>
        public GatewayAntivirusGatewayAntivirusRestrictMsOfficeMacros(bool http = default(bool), bool ftp = default(bool), bool imap = default(bool), bool smtp = default(bool), bool pop3 = default(bool), bool cifsNetbios = default(bool))
        {
            this.Http = http;
            this.Ftp = ftp;
            this.Imap = imap;
            this.Smtp = smtp;
            this.Pop3 = pop3;
            this.CifsNetbios = cifsNetbios;
        }

        /// <summary>
        /// HTTP.
        /// </summary>
        /// <value>HTTP.</value>
        [DataMember(Name = "http", EmitDefaultValue = true)]
        public bool Http { get; set; }

        /// <summary>
        /// FTP.
        /// </summary>
        /// <value>FTP.</value>
        [DataMember(Name = "ftp", EmitDefaultValue = true)]
        public bool Ftp { get; set; }

        /// <summary>
        /// IMAP.
        /// </summary>
        /// <value>IMAP.</value>
        [DataMember(Name = "imap", EmitDefaultValue = true)]
        public bool Imap { get; set; }

        /// <summary>
        /// SMTP.
        /// </summary>
        /// <value>SMTP.</value>
        [DataMember(Name = "smtp", EmitDefaultValue = true)]
        public bool Smtp { get; set; }

        /// <summary>
        /// POP3.
        /// </summary>
        /// <value>POP3.</value>
        [DataMember(Name = "pop3", EmitDefaultValue = true)]
        public bool Pop3 { get; set; }

        /// <summary>
        /// CIFS/NetBIOS.
        /// </summary>
        /// <value>CIFS/NetBIOS.</value>
        [DataMember(Name = "cifs_netbios", EmitDefaultValue = true)]
        public bool CifsNetbios { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class GatewayAntivirusGatewayAntivirusRestrictMsOfficeMacros {\n");
            sb.Append("  Http: ").Append(Http).Append("\n");
            sb.Append("  Ftp: ").Append(Ftp).Append("\n");
            sb.Append("  Imap: ").Append(Imap).Append("\n");
            sb.Append("  Smtp: ").Append(Smtp).Append("\n");
            sb.Append("  Pop3: ").Append(Pop3).Append("\n");
            sb.Append("  CifsNetbios: ").Append(CifsNetbios).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GatewayAntivirusGatewayAntivirusRestrictMsOfficeMacros);
        }

        /// <summary>
        /// Returns true if GatewayAntivirusGatewayAntivirusRestrictMsOfficeMacros instances are equal
        /// </summary>
        /// <param name="input">Instance of GatewayAntivirusGatewayAntivirusRestrictMsOfficeMacros to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GatewayAntivirusGatewayAntivirusRestrictMsOfficeMacros input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Http == input.Http ||
                    this.Http.Equals(input.Http)
                ) && 
                (
                    this.Ftp == input.Ftp ||
                    this.Ftp.Equals(input.Ftp)
                ) && 
                (
                    this.Imap == input.Imap ||
                    this.Imap.Equals(input.Imap)
                ) && 
                (
                    this.Smtp == input.Smtp ||
                    this.Smtp.Equals(input.Smtp)
                ) && 
                (
                    this.Pop3 == input.Pop3 ||
                    this.Pop3.Equals(input.Pop3)
                ) && 
                (
                    this.CifsNetbios == input.CifsNetbios ||
                    this.CifsNetbios.Equals(input.CifsNetbios)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Http.GetHashCode();
                hashCode = (hashCode * 59) + this.Ftp.GetHashCode();
                hashCode = (hashCode * 59) + this.Imap.GetHashCode();
                hashCode = (hashCode * 59) + this.Smtp.GetHashCode();
                hashCode = (hashCode * 59) + this.Pop3.GetHashCode();
                hashCode = (hashCode * 59) + this.CifsNetbios.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
