/*
 * SonicOS API
 *
 * __Swagger Specification for SonicOS APIs__  ___SonicOS support two-factor and bearer token login from SWAGGER only.___  Please follow the following steps to login. > 1. POST \"tfa\" with your username, password, and two-factor code to the firewall. If you are authenticating a username for the first time, please login to GUI and scan the QR code to activate two-factor authentication. > 2. The Bearer Token is returned in response to the \"tfa\" message. Copy the Bearer Token to the \"Authorize\" button. > 3. DELETE \"auth\" to logout of the current session. 
 *
 * The version of the OpenAPI document: 7.0.1
 * Contact: sonicOsApiSupport@SonicWall.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = SonicWallGen7.Client.OpenAPIDateConverter;

namespace SonicWallGen7.Model
{
    /// <summary>
    /// LDAP search test. This test will have basic and advanced modes.
    /// </summary>
    [DataContract(Name = "user_ldap_test_advanced_search_user_ldap_test_type_ldap_search")]
    public partial class UserLdapTestAdvancedSearchUserLdapTestTypeLdapSearch : IEquatable<UserLdapTestAdvancedSearchUserLdapTestTypeLdapSearch>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="UserLdapTestAdvancedSearchUserLdapTestTypeLdapSearch" /> class.
        /// </summary>
        /// <param name="returnAttribute">The return attributes will allow specifying a list of the attributes                to return and display rather than displaying the entire matched entry..</param>
        /// <param name="filter">filter.</param>
        public UserLdapTestAdvancedSearchUserLdapTestTypeLdapSearch(string returnAttribute = default(string), UserLdapTestAdvancedSearchUserLdapTestTypeLdapSearchFilter filter = default(UserLdapTestAdvancedSearchUserLdapTestTypeLdapSearchFilter))
        {
            this.ReturnAttribute = returnAttribute;
            this.Filter = filter;
        }

        /// <summary>
        /// The return attributes will allow specifying a list of the attributes                to return and display rather than displaying the entire matched entry.
        /// </summary>
        /// <value>The return attributes will allow specifying a list of the attributes                to return and display rather than displaying the entire matched entry.</value>
        [DataMember(Name = "return_attribute", EmitDefaultValue = false)]
        public string ReturnAttribute { get; set; }

        /// <summary>
        /// Gets or Sets Filter
        /// </summary>
        [DataMember(Name = "filter", EmitDefaultValue = false)]
        public UserLdapTestAdvancedSearchUserLdapTestTypeLdapSearchFilter Filter { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class UserLdapTestAdvancedSearchUserLdapTestTypeLdapSearch {\n");
            sb.Append("  ReturnAttribute: ").Append(ReturnAttribute).Append("\n");
            sb.Append("  Filter: ").Append(Filter).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as UserLdapTestAdvancedSearchUserLdapTestTypeLdapSearch);
        }

        /// <summary>
        /// Returns true if UserLdapTestAdvancedSearchUserLdapTestTypeLdapSearch instances are equal
        /// </summary>
        /// <param name="input">Instance of UserLdapTestAdvancedSearchUserLdapTestTypeLdapSearch to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(UserLdapTestAdvancedSearchUserLdapTestTypeLdapSearch input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.ReturnAttribute == input.ReturnAttribute ||
                    (this.ReturnAttribute != null &&
                    this.ReturnAttribute.Equals(input.ReturnAttribute))
                ) && 
                (
                    this.Filter == input.Filter ||
                    (this.Filter != null &&
                    this.Filter.Equals(input.Filter))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ReturnAttribute != null)
                {
                    hashCode = (hashCode * 59) + this.ReturnAttribute.GetHashCode();
                }
                if (this.Filter != null)
                {
                    hashCode = (hashCode * 59) + this.Filter.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
