/*
 * SonicOS API
 *
 * __Swagger Specification for SonicOS APIs__  ___SonicOS support two-factor and bearer token login from SWAGGER only.___  Please follow the following steps to login. > 1. POST \"tfa\" with your username, password, and two-factor code to the firewall. If you are authenticating a username for the first time, please login to GUI and scan the QR code to activate two-factor authentication. > 2. The Bearer Token is returned in response to the \"tfa\" message. Copy the Bearer Token to the \"Authorize\" button. > 3. DELETE \"auth\" to logout of the current session. 
 *
 * The version of the OpenAPI document: 7.0.1
 * Contact: sonicOsApiSupport@SonicWall.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = SonicWallGen7.Client.OpenAPIDateConverter;
using System.Reflection;

namespace SonicWallGen7.Model
{
    /// <summary>
    /// Set the IP address pool.
    /// </summary>
    [JsonConverter(typeof(VpnL2tpServerVpnL2tpServerIpPoolJsonConverter))]
    [DataContract(Name = "vpn_l2tp_server_vpn_l2tp_server_ip_pool")]
    public partial class VpnL2tpServerVpnL2tpServerIpPool : AbstractOpenAPISchema, IEquatable<VpnL2tpServerVpnL2tpServerIpPool>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="VpnL2tpServerVpnL2tpServerIpPool" /> class
        /// with the <see cref="VpnL2tpServerL2tpServerIpPoolProvided" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of VpnL2tpServerL2tpServerIpPoolProvided.</param>
        public VpnL2tpServerVpnL2tpServerIpPool(VpnL2tpServerL2tpServerIpPoolProvided actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="VpnL2tpServerVpnL2tpServerIpPool" /> class
        /// with the <see cref="VpnL2tpServerL2tpServerIpPoolLocal" /> class
        /// </summary>
        /// <param name="actualInstance">An instance of VpnL2tpServerL2tpServerIpPoolLocal.</param>
        public VpnL2tpServerVpnL2tpServerIpPool(VpnL2tpServerL2tpServerIpPoolLocal actualInstance)
        {
            this.IsNullable = false;
            this.SchemaType= "oneOf";
            this.ActualInstance = actualInstance ?? throw new ArgumentException("Invalid instance found. Must not be null.");
        }


        private Object _actualInstance;

        /// <summary>
        /// Gets or Sets ActualInstance
        /// </summary>
        public override Object ActualInstance
        {
            get
            {
                return _actualInstance;
            }
            set
            {
                if (value.GetType() == typeof(VpnL2tpServerL2tpServerIpPoolLocal))
                {
                    this._actualInstance = value;
                }
                else if (value.GetType() == typeof(VpnL2tpServerL2tpServerIpPoolProvided))
                {
                    this._actualInstance = value;
                }
                else
                {
                    throw new ArgumentException("Invalid instance found. Must be the following types: VpnL2tpServerL2tpServerIpPoolLocal, VpnL2tpServerL2tpServerIpPoolProvided");
                }
            }
        }

        /// <summary>
        /// Get the actual instance of `VpnL2tpServerL2tpServerIpPoolProvided`. If the actual instance is not `VpnL2tpServerL2tpServerIpPoolProvided`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of VpnL2tpServerL2tpServerIpPoolProvided</returns>
        public VpnL2tpServerL2tpServerIpPoolProvided GetVpnL2tpServerL2tpServerIpPoolProvided()
        {
            return (VpnL2tpServerL2tpServerIpPoolProvided)this.ActualInstance;
        }

        /// <summary>
        /// Get the actual instance of `VpnL2tpServerL2tpServerIpPoolLocal`. If the actual instance is not `VpnL2tpServerL2tpServerIpPoolLocal`,
        /// the InvalidClassException will be thrown
        /// </summary>
        /// <returns>An instance of VpnL2tpServerL2tpServerIpPoolLocal</returns>
        public VpnL2tpServerL2tpServerIpPoolLocal GetVpnL2tpServerL2tpServerIpPoolLocal()
        {
            return (VpnL2tpServerL2tpServerIpPoolLocal)this.ActualInstance;
        }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class VpnL2tpServerVpnL2tpServerIpPool {\n");
            sb.Append("  ActualInstance: ").Append(this.ActualInstance).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this.ActualInstance, VpnL2tpServerVpnL2tpServerIpPool.SerializerSettings);
        }

        /// <summary>
        /// Converts the JSON string into an instance of VpnL2tpServerVpnL2tpServerIpPool
        /// </summary>
        /// <param name="jsonString">JSON string</param>
        /// <returns>An instance of VpnL2tpServerVpnL2tpServerIpPool</returns>
        public static VpnL2tpServerVpnL2tpServerIpPool FromJson(string jsonString)
        {
            VpnL2tpServerVpnL2tpServerIpPool newVpnL2tpServerVpnL2tpServerIpPool = null;

            if (string.IsNullOrEmpty(jsonString))
            {
                return newVpnL2tpServerVpnL2tpServerIpPool;
            }
            int match = 0;
            List<string> matchedTypes = new List<string>();

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(VpnL2tpServerL2tpServerIpPoolLocal).GetProperty("AdditionalProperties") == null)
                {
                    newVpnL2tpServerVpnL2tpServerIpPool = new VpnL2tpServerVpnL2tpServerIpPool(JsonConvert.DeserializeObject<VpnL2tpServerL2tpServerIpPoolLocal>(jsonString, VpnL2tpServerVpnL2tpServerIpPool.SerializerSettings));
                }
                else
                {
                    newVpnL2tpServerVpnL2tpServerIpPool = new VpnL2tpServerVpnL2tpServerIpPool(JsonConvert.DeserializeObject<VpnL2tpServerL2tpServerIpPoolLocal>(jsonString, VpnL2tpServerVpnL2tpServerIpPool.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("VpnL2tpServerL2tpServerIpPoolLocal");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into VpnL2tpServerL2tpServerIpPoolLocal: {1}", jsonString, exception.ToString()));
            }

            try
            {
                // if it does not contains "AdditionalProperties", use SerializerSettings to deserialize
                if (typeof(VpnL2tpServerL2tpServerIpPoolProvided).GetProperty("AdditionalProperties") == null)
                {
                    newVpnL2tpServerVpnL2tpServerIpPool = new VpnL2tpServerVpnL2tpServerIpPool(JsonConvert.DeserializeObject<VpnL2tpServerL2tpServerIpPoolProvided>(jsonString, VpnL2tpServerVpnL2tpServerIpPool.SerializerSettings));
                }
                else
                {
                    newVpnL2tpServerVpnL2tpServerIpPool = new VpnL2tpServerVpnL2tpServerIpPool(JsonConvert.DeserializeObject<VpnL2tpServerL2tpServerIpPoolProvided>(jsonString, VpnL2tpServerVpnL2tpServerIpPool.AdditionalPropertiesSerializerSettings));
                }
                matchedTypes.Add("VpnL2tpServerL2tpServerIpPoolProvided");
                match++;
            }
            catch (Exception exception)
            {
                // deserialization failed, try the next one
                System.Diagnostics.Debug.WriteLine(string.Format("Failed to deserialize `{0}` into VpnL2tpServerL2tpServerIpPoolProvided: {1}", jsonString, exception.ToString()));
            }

            if (match == 0)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` cannot be deserialized into any schema defined.");
            }
            else if (match > 1)
            {
                throw new InvalidDataException("The JSON string `" + jsonString + "` incorrectly matches more than one schema (should be exactly one match): " + String.Join(",", matchedTypes));
            }

            // deserialization is considered successful at this point if no exception has been thrown.
            return newVpnL2tpServerVpnL2tpServerIpPool;
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VpnL2tpServerVpnL2tpServerIpPool);
        }

        /// <summary>
        /// Returns true if VpnL2tpServerVpnL2tpServerIpPool instances are equal
        /// </summary>
        /// <param name="input">Instance of VpnL2tpServerVpnL2tpServerIpPool to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VpnL2tpServerVpnL2tpServerIpPool input)
        {
            if (input == null)
                return false;

            return this.ActualInstance.Equals(input.ActualInstance);
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ActualInstance != null)
                    hashCode = hashCode * 59 + this.ActualInstance.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// Custom JSON converter for VpnL2tpServerVpnL2tpServerIpPool
    /// </summary>
    public class VpnL2tpServerVpnL2tpServerIpPoolJsonConverter : JsonConverter
    {
        /// <summary>
        /// To write the JSON string
        /// </summary>
        /// <param name="writer">JSON writer</param>
        /// <param name="value">Object to be converted into a JSON string</param>
        /// <param name="serializer">JSON Serializer</param>
        public override void WriteJson(JsonWriter writer, object value, JsonSerializer serializer)
        {
            writer.WriteRawValue((string)(typeof(VpnL2tpServerVpnL2tpServerIpPool).GetMethod("ToJson").Invoke(value, null)));
        }

        /// <summary>
        /// To convert a JSON string into an object
        /// </summary>
        /// <param name="reader">JSON reader</param>
        /// <param name="objectType">Object type</param>
        /// <param name="existingValue">Existing value</param>
        /// <param name="serializer">JSON Serializer</param>
        /// <returns>The object converted from the JSON string</returns>
        public override object ReadJson(JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer)
        {
            if(reader.TokenType != JsonToken.Null)
            {
                return VpnL2tpServerVpnL2tpServerIpPool.FromJson(JObject.Load(reader).ToString(Formatting.None));
            }
            return null;
        }

        /// <summary>
        /// Check if the object can be converted
        /// </summary>
        /// <param name="objectType">Object type</param>
        /// <returns>True if the object can be converted</returns>
        public override bool CanConvert(Type objectType)
        {
            return false;
        }
    }

}
