/*
 * SonicOS API
 *
 * __Swagger Specification for SonicOS APIs__  ___SonicOS support two-factor and bearer token login from SWAGGER only.___  Please follow the following steps to login. > 1. POST \"tfa\" with your username, password, and two-factor code to the firewall. If you are authenticating a username for the first time, please login to GUI and scan the QR code to activate two-factor authentication. > 2. The Bearer Token is returned in response to the \"tfa\" message. Copy the Bearer Token to the \"Authorize\" button. > 3. DELETE \"auth\" to logout of the current session. 
 *
 * The version of the OpenAPI document: 7.0.1
 * Contact: sonicOsApiSupport@SonicWall.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = SonicWallGen7.Client.OpenAPIDateConverter;

namespace SonicWallGen7.Model
{
    /// <summary>
    /// VPN L2TP server PPP settings.
    /// </summary>
    [DataContract(Name = "vpn_l2tp_server_ppp")]
    public partial class VpnL2tpServerPpp : IEquatable<VpnL2tpServerPpp>, IValidatableObject
    {
        /// <summary>
        /// Remove PPP authentication protocol.
        /// </summary>
        /// <value>Remove PPP authentication protocol.</value>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum ProtocolEnum
        {
            /// <summary>
            /// Enum Pap for value: pap
            /// </summary>
            [EnumMember(Value = "pap")]
            Pap = 1,

            /// <summary>
            /// Enum Mschap for value: mschap
            /// </summary>
            [EnumMember(Value = "mschap")]
            Mschap = 2,

            /// <summary>
            /// Enum Mschapv2 for value: mschapv2
            /// </summary>
            [EnumMember(Value = "mschapv2")]
            Mschapv2 = 3,

            /// <summary>
            /// Enum Chap for value: chap
            /// </summary>
            [EnumMember(Value = "chap")]
            Chap = 4
        }


        /// <summary>
        /// Remove PPP authentication protocol.
        /// </summary>
        /// <value>Remove PPP authentication protocol.</value>
        [DataMember(Name = "protocol", IsRequired = true, EmitDefaultValue = true)]
        public ProtocolEnum Protocol { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="VpnL2tpServerPpp" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected VpnL2tpServerPpp() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="VpnL2tpServerPpp" /> class.
        /// </summary>
        /// <param name="protocol">Remove PPP authentication protocol. (required).</param>
        /// <param name="order">PPP order (required).</param>
        public VpnL2tpServerPpp(ProtocolEnum protocol = default(ProtocolEnum), decimal order = default(decimal))
        {
            this.Protocol = protocol;
            this.Order = order;
        }

        /// <summary>
        /// PPP order
        /// </summary>
        /// <value>PPP order</value>
        [DataMember(Name = "order", IsRequired = true, EmitDefaultValue = true)]
        public decimal Order { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class VpnL2tpServerPpp {\n");
            sb.Append("  Protocol: ").Append(Protocol).Append("\n");
            sb.Append("  Order: ").Append(Order).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as VpnL2tpServerPpp);
        }

        /// <summary>
        /// Returns true if VpnL2tpServerPpp instances are equal
        /// </summary>
        /// <param name="input">Instance of VpnL2tpServerPpp to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(VpnL2tpServerPpp input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Protocol == input.Protocol ||
                    this.Protocol.Equals(input.Protocol)
                ) && 
                (
                    this.Order == input.Order ||
                    this.Order.Equals(input.Order)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.Protocol.GetHashCode();
                hashCode = (hashCode * 59) + this.Order.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
