/*
 * SonicOS API
 *
 * __Swagger Specification for SonicOS APIs__  ___SonicOS support two-factor and bearer token login from SWAGGER only.___  Please follow the following steps to login. > 1. POST \"tfa\" with your username, password, and two-factor code to the firewall. If you are authenticating a username for the first time, please login to GUI and scan the QR code to activate two-factor authentication. > 2. The Bearer Token is returned in response to the \"tfa\" message. Copy the Bearer Token to the \"Authorize\" button. > 3. DELETE \"auth\" to logout of the current session. 
 *
 * The version of the OpenAPI document: 7.0.1
 * Contact: sonicOsApiSupport@SonicWall.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonicWallGen7.Model;
using SonicWallGen7.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonicWallGen7.Test.Model
{
    /// <summary>
    ///  Class for testing DhcpServerIpv6OptionObjectValueInner
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DhcpServerIpv6OptionObjectValueInnerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DhcpServerIpv6OptionObjectValueInner
        //private DhcpServerIpv6OptionObjectValueInner instance;

        public DhcpServerIpv6OptionObjectValueInnerTests()
        {
            // TODO uncomment below to create an instance of DhcpServerIpv6OptionObjectValueInner
            //instance = new DhcpServerIpv6OptionObjectValueInner();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DhcpServerIpv6OptionObjectValueInner
        /// </summary>
        [Fact]
        public void DhcpServerIpv6OptionObjectValueInnerInstanceTest()
        {
            // TODO uncomment below to test "IsType" DhcpServerIpv6OptionObjectValueInner
            //Assert.IsType<DhcpServerIpv6OptionObjectValueInner>(instance);
        }

        /// <summary>
        /// Test the property 'Ip'
        /// </summary>
        [Fact]
        public void IpTest()
        {
            // TODO unit test for the property 'Ip'
        }

        /// <summary>
        /// Test the property 'FourByte'
        /// </summary>
        [Fact]
        public void FourByteTest()
        {
            // TODO unit test for the property 'FourByte'
        }

        /// <summary>
        /// Test the property 'TwoByte'
        /// </summary>
        [Fact]
        public void TwoByteTest()
        {
            // TODO unit test for the property 'TwoByte'
        }

        /// <summary>
        /// Test the property 'OneByte'
        /// </summary>
        [Fact]
        public void OneByteTest()
        {
            // TODO unit test for the property 'OneByte'
        }

        /// <summary>
        /// Test the property 'VarString'
        /// </summary>
        [Fact]
        public void VarStringTest()
        {
            // TODO unit test for the property 'VarString'
        }

        /// <summary>
        /// Test the property 'Boolean'
        /// </summary>
        [Fact]
        public void BooleanTest()
        {
            // TODO unit test for the property 'Boolean'
        }

        /// <summary>
        /// Test the property 'DomainName'
        /// </summary>
        [Fact]
        public void DomainNameTest()
        {
            // TODO unit test for the property 'DomainName'
        }
    }
}
