/*
 * SonicOS API
 *
 * __Swagger Specification for SonicOS APIs__  ___SonicOS support two-factor and bearer token login from SWAGGER only.___  Please follow the following steps to login. > 1. POST \"tfa\" with your username, password, and two-factor code to the firewall. If you are authenticating a username for the first time, please login to GUI and scan the QR code to activate two-factor authentication. > 2. The Bearer Token is returned in response to the \"tfa\" message. Copy the Bearer Token to the \"Authorize\" button. > 3. DELETE \"auth\" to logout of the current session. 
 *
 * The version of the OpenAPI document: 7.0.1
 * Contact: sonicOsApiSupport@SonicWall.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonicWallGen7.Model;
using SonicWallGen7.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonicWallGen7.Test.Model
{
    /// <summary>
    ///  Class for testing LogAutomationLogAutomationMailServerAdvanced
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LogAutomationLogAutomationMailServerAdvancedTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LogAutomationLogAutomationMailServerAdvanced
        //private LogAutomationLogAutomationMailServerAdvanced instance;

        public LogAutomationLogAutomationMailServerAdvancedTests()
        {
            // TODO uncomment below to create an instance of LogAutomationLogAutomationMailServerAdvanced
            //instance = new LogAutomationLogAutomationMailServerAdvanced();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LogAutomationLogAutomationMailServerAdvanced
        /// </summary>
        [Fact]
        public void LogAutomationLogAutomationMailServerAdvancedInstanceTest()
        {
            // TODO uncomment below to test "IsType" LogAutomationLogAutomationMailServerAdvanced
            //Assert.IsType<LogAutomationLogAutomationMailServerAdvanced>(instance);
        }

        /// <summary>
        /// Test the property 'SmtpPort'
        /// </summary>
        [Fact]
        public void SmtpPortTest()
        {
            // TODO unit test for the property 'SmtpPort'
        }

        /// <summary>
        /// Test the property 'ConnectionSecurityMethod'
        /// </summary>
        [Fact]
        public void ConnectionSecurityMethodTest()
        {
            // TODO unit test for the property 'ConnectionSecurityMethod'
        }

        /// <summary>
        /// Test the property 'SmtpAuthentication'
        /// </summary>
        [Fact]
        public void SmtpAuthenticationTest()
        {
            // TODO unit test for the property 'SmtpAuthentication'
        }

        /// <summary>
        /// Test the property 'UserName'
        /// </summary>
        [Fact]
        public void UserNameTest()
        {
            // TODO unit test for the property 'UserName'
        }

        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }
    }
}
