/*
 * SonicOS API
 *
 * __Swagger Specification for SonicOS APIs__  ___SonicOS support two-factor and bearer token login from SWAGGER only.___  Please follow the following steps to login. > 1. POST \"tfa\" with your username, password, and two-factor code to the firewall. If you are authenticating a username for the first time, please login to GUI and scan the QR code to activate two-factor authentication. > 2. The Bearer Token is returned in response to the \"tfa\" message. Copy the Bearer Token to the \"Authorize\" button. > 3. DELETE \"auth\" to logout of the current session. 
 *
 * The version of the OpenAPI document: 7.0.1
 * Contact: sonicOsApiSupport@SonicWall.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonicWallGen7.Model;
using SonicWallGen7.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonicWallGen7.Test.Model
{
    /// <summary>
    ///  Class for testing ShowStatusTunnelInterfaceStatusDetail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ShowStatusTunnelInterfaceStatusDetailTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ShowStatusTunnelInterfaceStatusDetail
        //private ShowStatusTunnelInterfaceStatusDetail instance;

        public ShowStatusTunnelInterfaceStatusDetailTests()
        {
            // TODO uncomment below to create an instance of ShowStatusTunnelInterfaceStatusDetail
            //instance = new ShowStatusTunnelInterfaceStatusDetail();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ShowStatusTunnelInterfaceStatusDetail
        /// </summary>
        [Fact]
        public void ShowStatusTunnelInterfaceStatusDetailInstanceTest()
        {
            // TODO uncomment below to test "IsType" ShowStatusTunnelInterfaceStatusDetail
            //Assert.IsType<ShowStatusTunnelInterfaceStatusDetail>(instance);
        }

        /// <summary>
        /// Test the property 'InterfaceName'
        /// </summary>
        [Fact]
        public void InterfaceNameTest()
        {
            // TODO unit test for the property 'InterfaceName'
        }

        /// <summary>
        /// Test the property 'IpAddress'
        /// </summary>
        [Fact]
        public void IpAddressTest()
        {
            // TODO unit test for the property 'IpAddress'
        }

        /// <summary>
        /// Test the property 'SubnetMask'
        /// </summary>
        [Fact]
        public void SubnetMaskTest()
        {
            // TODO unit test for the property 'SubnetMask'
        }

        /// <summary>
        /// Test the property 'MtuValue'
        /// </summary>
        [Fact]
        public void MtuValueTest()
        {
            // TODO unit test for the property 'MtuValue'
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
    }
}
