/*
 * SonicOS API
 *
 * __Swagger Specification for SonicOS APIs__  ___SonicOS support two-factor and bearer token login from SWAGGER only.___  Please follow the following steps to login. > 1. POST \"tfa\" with your username, password, and two-factor code to the firewall. If you are authenticating a username for the first time, please login to GUI and scan the QR code to activate two-factor authentication. > 2. The Bearer Token is returned in response to the \"tfa\" message. Copy the Bearer Token to the \"Authorize\" button. > 3. DELETE \"auth\" to logout of the current session. 
 *
 * The version of the OpenAPI document: 7.0.1
 * Contact: sonicOsApiSupport@SonicWall.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using SonicWallGen7.Model;
using SonicWallGen7.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace SonicWallGen7.Test.Model
{
    /// <summary>
    ///  Class for testing SslControlBaseSslControl
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SslControlBaseSslControlTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SslControlBaseSslControl
        //private SslControlBaseSslControl instance;

        public SslControlBaseSslControlTests()
        {
            // TODO uncomment below to create an instance of SslControlBaseSslControl
            //instance = new SslControlBaseSslControl();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SslControlBaseSslControl
        /// </summary>
        [Fact]
        public void SslControlBaseSslControlInstanceTest()
        {
            // TODO uncomment below to test "IsType" SslControlBaseSslControl
            //Assert.IsType<SslControlBaseSslControl>(instance);
        }

        /// <summary>
        /// Test the property 'Enable'
        /// </summary>
        [Fact]
        public void EnableTest()
        {
            // TODO unit test for the property 'Enable'
        }

        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Fact]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }

        /// <summary>
        /// Test the property 'Blacklist'
        /// </summary>
        [Fact]
        public void BlacklistTest()
        {
            // TODO unit test for the property 'Blacklist'
        }

        /// <summary>
        /// Test the property 'Whitelist'
        /// </summary>
        [Fact]
        public void WhitelistTest()
        {
            // TODO unit test for the property 'Whitelist'
        }

        /// <summary>
        /// Test the property 'Detect'
        /// </summary>
        [Fact]
        public void DetectTest()
        {
            // TODO unit test for the property 'Detect'
        }
    }
}
